# Generated by Django 3.1.4 on 2021-01-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
