# Generated by Django 3.1.4 on 2021-01-24 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210123_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderproduct'),
        ),
    ]
